{
 "title": "CCE NODE  2(10.166.240.70) HTTP",
 "time": { "from": "2025-02-24T10:44:18.336Z", "to": "2025-02-24T10:45:46.919Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Instantaneous Download Speed (MB/s)",
   "type": "gauge",
   "description": "Displays the current real-time download speed in Megabytes per second (MB/s). This gauge provides an instant snapshot of network performance during an ongoing speed test.\n\n",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    strftime('%Y-%m-%dT%H:%M:%S', timestamp) || '+05:30' AS time,  -- Keep it in IST format\n    download_speed_mbps AS value,  -- The numerical value Grafana will plot (download speed)\n    node_ip,\n    'Download_speed_Mbps' AS metric  -- A label for the metric\nFROM \n    speedtest_results\nWHERE \n    node_ip IN ('10.166.240.70')\nORDER BY \n    time ASC;  -- Grafana expects time-series data in ascending order\n\n\n",
     "rawQueryText": "SELECT \n    strftime('%Y-%m-%dT%H:%M:%S', timestamp) || '+05:30' AS time,  -- Keep it in IST format\n    download_speed_mbps AS value,  -- The numerical value Grafana will plot (download speed)\n    node_ip,\n    'Download_speed_Mbps' AS metric  -- A label for the metric\nFROM \n    speedtest_results\nWHERE \n    node_ip IN ('10.166.240.70')\nORDER BY \n    time ASC;  -- Grafana expects time-series data in ascending order\n\n\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Live Download Speed Trend (MB/s vs Time)",
   "type": "timeseries",
   "description": "Plots real-time download speed against time, tracking speed fluctuations during a test. This panel aids in identifying performance trends and inconsistencies.\n\n",
   "gridPos": { "h": 14, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n    strftime('%Y-%m-%dT%H:%M:%S', timestamp) || '+05:30' AS time,  -- Keep it in IST format\n    download_speed_mbps AS value,  -- The numerical value Grafana will plot (download speed)\n    node_ip,\n    'Download_speed_Mbps' AS metric  -- A label for the metric\nFROM \n    speedtest_results\nWHERE \n    node_ip IN ('10.166.240.70')\nORDER BY \n    time ASC;  -- Grafana expects time-series data in ascending order\n",
     "rawQueryText": "SELECT \n    strftime('%Y-%m-%dT%H:%M:%S', timestamp) || '+05:30' AS time,  -- Keep it in IST format\n    download_speed_mbps AS value,  -- The numerical value Grafana will plot (download speed)\n    node_ip,\n    'Download_speed_Mbps' AS metric  -- A label for the metric\nFROM \n    speedtest_results\nWHERE \n    node_ip IN ('10.166.240.70')\nORDER BY \n    time ASC;  -- Grafana expects time-series data in ascending order\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Download Speed Distribution (MB/s)",
   "type": "piechart",
   "description": "Categorizes download speeds into three ranges: below 1 MB/s, 1 - 2.75 MB/s, and above 2.75 MB/s. This visualisation helps assess overall network speed consistency.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "SELECT \n    CASE  \n        WHEN download_speed_mbps < 1 THEN 'Below 1 MB/s'  \n        WHEN download_speed_mbps BETWEEN 1 AND 2.75 THEN '1 - 2.75 MB/s'  \n        ELSE 'Above 2.75 MB/s'  \n    END AS metric,\n    (COUNT(*) * 100.0) / (SELECT COUNT(*) FROM speedtest_results WHERE node_ip = '10.166.240.70') AS value\nFROM \n    speedtest_results  \nWHERE \n    node_ip = '10.166.240.70'  \nGROUP BY \n    metric",
     "rawQueryText": "SELECT \n    CASE  \n        WHEN download_speed_mbps < 1 THEN 'Below 1 MB/s'  \n        WHEN download_speed_mbps BETWEEN 1 AND 2.75 THEN '1 - 2.75 MB/s'  \n        ELSE 'Above 2.75 MB/s'  \n    END AS metric,\n    (COUNT(*) * 100.0) / (SELECT COUNT(*) FROM speedtest_results WHERE node_ip = '10.166.240.70') AS value\nFROM \n    speedtest_results  \nWHERE \n    node_ip = '10.166.240.70'  \nGROUP BY \n    metric",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Download Speed Trend (MB/s vs Time)",
   "type": "timeseries",
   "description": "Plots real-time download speed against time, tracking speed fluctuations during a test. This panel aids in identifying performance trends and inconsistencies.\n\n",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "queryText": "SELECT \n    strftime('%Y-%m-%dT%H:%M:%S', timestamp) || '+05:30' AS time,  -- Keep it in IST format\n    download_speed_mbps AS value,  -- The numerical value Grafana will plot (download speed)\n    node_ip,\n    'Download_speed_Mbps' AS metric  -- A label for the metric\nFROM \n    speedtest_results\nWHERE \n    node_ip IN ('10.166.240.70')\n   \nORDER BY \n    time ASC;  -- Grafana expects time-series data in ascending order\n",
     "rawQueryText": "SELECT \n    strftime('%Y-%m-%dT%H:%M:%S', timestamp) || '+05:30' AS time,  -- Keep it in IST format\n    download_speed_mbps AS value,  -- The numerical value Grafana will plot (download speed)\n    node_ip,\n    'Download_speed_Mbps' AS metric  -- A label for the metric\nFROM \n    speedtest_results\nWHERE \n    node_ip IN ('10.166.240.70')\n   \nORDER BY \n    time ASC;  -- Grafana expects time-series data in ascending order\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}